# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75a3617dfbadbc924bcee2d52cbfb61633d8fcc06567a93a05c2b828ead319456980c22050671c44d5320cf8fd56622a7c1d297a217fd5f558ec477355f6f9d8

test:
  secret_key_base: b5788c5f7982569eb2d1270b6c2d26f56d5e6054bac3bb5dbff6bddeeecb5f1c78b9fa490495eb9e8bbaef7ebd56bd303622d1b5f80ae802b65e116549d6c9ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
